export const MENU_ITEMS = Object.freeze({
  CENTER: [
    { label: 'model S', to: '/' },
    { label: 'model 3', to: '/' },
    { label: 'model X', to: '/' },
    { label: 'model Y', to: '/' },
    { label: 'solar roof', to: '/' },
    { label: 'solar panels', to: '/' },
    { label: 'powerwall', to: '/' },
  ],
  RIGHT: [
    { label: 'shop', to: '/' },
    { label: 'account', to: '/' },
    { label: 'menu', to: '/', dataName: 'menu' },
  ],
  PANEL: [
    { label: 'Existing Inventory' },
    { label: 'Used Inventory' },
    { label: 'Trade-In' },
    { label: 'Demo Drive' },
    { label: 'Insurance' },
    { label: 'Fleet' },
    { label: 'Cybertruck' },
    { label: 'Roadster' },
    { label: 'Semi' },
    { label: 'Charging' },
    { label: 'Commercial Energy' },
    { label: 'Utilities' },
    { label: 'Careers' },
    { label: 'Find Us' },
    { label: 'Events' },
    { label: 'Support' },
    { label: 'Investor Relations' },
  ]
})
